name: Run setup.sh on different operating systems
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Run-setup-script-on-Ubuntu:
    name: Run setup.sh on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          set -x
          source ./setup.sh

  Run-setup-script-on-Mac:
    name: Run setup.sh on MacOS 14 Sonoma
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: Run setup.sh with bash
        shell: bash
        run: |
          set -x
          trap '' PIPE
          yes 2>/dev/null | source ./setup.sh
          trap - PIPE
      - name: Run setup.sh with zsh
        shell: zsh {0}
        run: |
          set -x
          yes 2>/dev/null | source ./setup.sh
