name: Run setup.sh on different operating systems
on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '12 3 * * 5'

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          ignore_names: >-
            .bashrc
            .bash_profile
            .zshrc

  Run-setup-script-on-Ubuntu:
    name: Run setup.sh on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run setup.sh
        run: |
          echo $SHELL
          set -x
          yes 2>/dev/null | source ./setup.sh

  Run-setup-script-with-Bash-on-Mac:
    name: Run setup.sh with Bash on MacOS 15 Sequoia
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - name: Run setup.sh with bash
        shell: bash
        run: |
          set -x
          set +e +o pipefail # ref. https://maku693.hatenablog.jp/entry/2021/01/08/220041
          yes 2>/dev/null | source ./setup.sh

  Run-setup-script-with-Zsh-on-Mac:
    name: Run setup.sh with Zsh on MacOS 15 Sequoia
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - name: Run setup.sh with zsh
        # ref. https://zenn.dev/shundeveloper/articles/2fdf4bf627072f
        shell: zsh {0}
        run: |
          set -x
          yes 2>/dev/null | source ./setup.sh

  Run-sheldon-with-Zsh-on-Mac:
    name: Run sheldon with Zsh on MacOS 15 Sequoia
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - name: Fetch sheldon then run
        shell: zsh {0}
        run: |
          curl -v --proto '=https' -fLsS https://rossmacarthur.github.io/install/crate.sh | bash -s -- --repo rossmacarthur/sheldon --to ~/.local/bin
          mkdir -p ~/.config/sheldon
          ln -svni "$(pwd)"/sheldon/plugins.toml ~/.config/sheldon/
          eval "$(~/.local/bin/sheldon source)"
          if ! tail -n+1 ~/.local/share/sheldon/plugins.lock ; then
            exit 1
          fi
          zstyle

  vim-lint:
    name: Lint Vim Scripts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Upgrade pip and install build tools
        run: python -m pip install --upgrade pip setuptools wheel
      - name: Install vint
        run: pip install vim-vint
      - name: Run vint
        run: vint .vimrc .vimrc.bundle .vim/

      - name: Notify status to Discord
        uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
          title: "Vint Linting"
